### ISSUE TITLE
Build panicking during normal testing, but compilation passing (erroneously) with TryBuild

### ISSUE THREAD

**Issue by koenichiwa** [dtolnay/trybuild#242] opened 2023-09-15 12:44 UTC
I have this piece of code which I'm running through TryBuild. In actuallity its part of a proc_macro which creates a builder that has a lot of const generics, and I'm trying to check during compilation time if all prerequisites are met. 

In this example I severely simplified the expanded macro and ran the supplied example through trybuild, standard tests, and doctests (with the `compile_fail` and `should_panic` flags). TryBuild seems to pass the compilation, yet the other types of tests seem to fail during the compilation step. 

I really need to test if compilation works because thats the main feature of this crate. I was hoping you could help me with finding out why there's a discrepancy with `cargo build` and testing with trybuild. I dumped a lot of logging below, I hope it helps

The example code:
```rust
// failing_test.rs
fn main() {
    pub struct Foo { }

    impl Foo {
        fn builder() -> FooBuilder<false> {
            FooBuilder::new()
        }
    }
    
    pub struct FooBuilder<const BAZ_0: bool>;
    impl FooBuilder<false> {
        pub fn new() -> FooBuilder<false> {
            FooBuilder { }
        }
    }
    impl<const BAZ_0: bool> FooBuilder<BAZ_0> {
        const GROUP_VERIFIER: () = {
            if !BAZ_0 {
                panic!(
                    "`.build()` failed because the bounds of group `baz` where not met (at_least 2)"
                );
            }
            ()
        };
        pub fn build(self) -> Foo {
            let _ = Self::GROUP_VERIFIER;
            Foo { }
        }
    }

    let _foo = Foo::builder().build();
}
```
doctest with `compile_fail` passes. This is expected behaviour.
```
test src/lib.rs - (line 2) - compile fail ... ok
```
But everything else fails:

trybuild output + full backtrace:
```
test ./compile_fail/failing_test.rs ... error
Expected test case to fail to compile, but it succeeded.

---- test::compile_fail_tests stdout ----
thread 'test::compile_fail_tests' panicked at '1 of 10 tests failed', /Users/koen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/trybuild-1.0.84/src/run.rs:101:13
stack backtrace:
   0:        0x102491bf3 - std::backtrace_rs::backtrace::libunwind::trace::h14243dc752b5beac
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x102491bf3 - std::backtrace_rs::backtrace::trace_unsynchronized::h71ecb3a9455536a6
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x102491bf3 - std::sys_common::backtrace::_print_fmt::h7e307467d6e88eaf
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:65:5
   3:        0x102491bf3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he60192cdeae7ff98
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x1024b554b - core::fmt::rt::Argument::fmt::hef24bdd6ecabdaa4
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/rt.rs:138:9
   5:        0x1024b554b - core::fmt::write::hccf73e6ac9b102cd
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/mod.rs:1094:21
   6:        0x10248d7de - std::io::Write::write_fmt::h314b25410ac6558c
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/io/mod.rs:1714:15
   7:        0x1024919ea - std::sys_common::backtrace::_print::h57786acb50d0c08a
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x1024919ea - std::sys_common::backtrace::print::h57a90601b74ca1dc
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x102493635 - std::panicking::default_hook::{{closure}}::h8463146ca7fe4cbf
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:269:22
  10:        0x102493378 - std::panicking::default_hook::h473c81bbe30d7761
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:285:9
  11:        0x10245c0b4 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h722eadf9af7f73c2
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:2007:9
  12:        0x10245c0b4 - test::test_main::{{closure}}::h1a1652efdc7b7ba0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/test/src/lib.rs:135:21
  13:        0x102493d6e - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::he523c9b219f9b982
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:2007:9
  14:        0x102493d6e - std::panicking::rust_panic_with_hook::h0ff95e3e20549b0d
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:709:13
  15:        0x102493b13 - std::panicking::begin_panic_handler::{{closure}}::h5e967ae12a1d4ba1
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:597:13
  16:        0x102491ff9 - std::sys_common::backtrace::__rust_end_short_backtrace::h5c230463e113192d
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:151:18
  17:        0x10249384d - rust_begin_unwind
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
  18:        0x1024b36c3 - core::panicking::panic_fmt::h9d91d0e3e7a6cd1a
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
  19:        0x1023ae675 - trybuild::run::<impl trybuild::Runner>::run::h82082fdd007106ba
                               at /Users/koen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/trybuild-1.0.84/src/run.rs:101:13
  20:        0x1023b36ba - <trybuild::TestCases as core::ops::drop::Drop>::drop::hb641885fea5cc28d
                               at /Users/koen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/trybuild-1.0.84/src/lib.rs:315:13
  21:        0x102247895 - core::ptr::drop_in_place<trybuild::TestCases>::h04e3e218bbd69b1b
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ptr/mod.rs:497:1
  22:        0x102248e4b - const_typed_builder_test::test::compile_fail_tests::h8f4ff7305d2be613
                               at /Users/koen/Projects/const_typed_builder/const_typed_builder_test/src/lib.rs:51:5
  23:        0x102242bf9 - const_typed_builder_test::test::compile_fail_tests::{{closure}}::hd8f5af876f198f31
                               at /Users/koen/Projects/const_typed_builder/const_typed_builder_test/src/lib.rs:42:29
  24:        0x102247048 - core::ops::function::FnOnce::call_once::hb4171cd731908658
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
  25:        0x102460af2 - core::ops::function::FnOnce::call_once::h331e452c27c76fca
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
  26:        0x102460af2 - test::__rust_begin_short_backtrace::h6ad65b3a26c794ae
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/test/src/lib.rs:626:18
  27:        0x10245f8a2 - test::run_test_in_process::{{closure}}::h6dec5d8067344610
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/test/src/lib.rs:649:60
  28:        0x10245f8a2 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h34717042aef63b28
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panic/unwind_safe.rs:271:9
  29:        0x10245f8a2 - std::panicking::try::do_call::h7129be5828e58a9a
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  30:        0x10245f8a2 - std::panicking::try::hd62fcb2b6dba651c
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  31:        0x10245f8a2 - std::panic::catch_unwind::h44135775c97a4f8f
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  32:        0x10245f8a2 - test::run_test_in_process::h4577a6d5ab2a020e
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/test/src/lib.rs:649:27
  33:        0x10245f8a2 - test::run_test::{{closure}}::hf59b79eb064b4c77
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/test/src/lib.rs:572:43
  34:        0x102424a61 - test::run_test::{{closure}}::hb1954f02fc093d82
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/test/src/lib.rs:600:41
  35:        0x102424a61 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha0bf8dcc6c2f0762
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.rs:135:18
  36:        0x10242a9cb - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h608985172358da9f
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/thread/mod.rs:529:17
  37:        0x10242a9cb - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h459a2921d28caea3
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panic/unwind_safe.rs:271:9
  38:        0x10242a9cb - std::panicking::try::do_call::h07431c058ca16d27
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  39:        0x10242a9cb - std::panicking::try::h38ab4229ec41f8c0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  40:        0x10242a9cb - std::panic::catch_unwind::h91a4e9aa77afd97f
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  41:        0x10242a9cb - std::thread::Builder::spawn_unchecked_::{{closure}}::h987340c56f937359
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/thread/mod.rs:528:30
  42:        0x10242a9cb - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd7cc2bce052ba999
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:5
  43:        0x102498ad9 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd3f407e37d0997c0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:1993:9
  44:        0x102498ad9 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha379d05e5207e350
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/alloc/src/boxed.rs:1993:9
  45:        0x102498ad9 - std::sys::unix::thread::Thread::new::thread_start::ha4a6ad20828e5661
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys/unix/thread.rs:108:17
  46:     0x7fff55545661 - __pthread_body
  47:     0x7fff5554550d - __pthread_start
```

When ran through the standard test suite it fails to compile, also expected behaviour. If I try to run all tests it already stops before running any tests, but in the compilation phase.
```
   Compiling const_typed_builder_test v0.1.1 (/Users/koen/Projects/const_typed_builder/const_typed_builder_test)
error[E0080]: evaluation of `test::failing_test::FooBuilder::<false>::GROUP_VERIFIER` failed
  --> const_typed_builder_test/src/lib.rs:26:21
   |
26 | /                     panic!(
27 | |                         "`.build()` failed because the bounds of group `baz` where not met (at_least 2)"
28 | |                     );
   | |_____________________^ the evaluated program panicked at '`.build()` failed because the bounds of group `baz` where not met (at_least 2)', const_typed_builder_test/src/lib.rs:26:21
   |
   = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)

note: the above error was encountered while instantiating `fn test::failing_test::FooBuilder::<false>::build`
  --> const_typed_builder_test/src/lib.rs:38:20
   |
38 |         let _foo = Foo::builder().build();
   |                    ^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0080`.
error: could not compile `const_typed_builder_test` (lib test) due to previous error
```

doctest with `should_panic` also fails, again expected behaviour. It panics during compilation, not while running.
```
---- src/lib.rs - (line 2) stdout ----
error[E0080]: evaluation of `main::_doctest_main_src_lib_rs_2_0::FooBuilder::<false>::GROUP_VERIFIER` failed
  --> src/lib.rs:20:13
   |
20 | /             panic!(
21 | |                 "`.build()` failed because the bounds of group `baz` where not met (at_least 2)"
22 | |             );
   | |_____________^ the evaluated program panicked at '`.build()` failed because the bounds of group `baz` where not met (at_least 2)', src/lib.rs:20:13
   |
   = note: this error originates in the macro `$crate::panic::panic_2021` which comes from the expansion of the macro `panic` (in Nightly builds, run with -Z macro-backtrace for more info)

note: the above error was encountered while instantiating `fn main::_doctest_main_src_lib_rs_2_0::FooBuilder::<false>::build`
  --> src/lib.rs:32:12
   |
32 | let _foo = Foo::builder().build();
   |            ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0080`.
Couldn't compile the test.
```

**Comment by dtolnay** [comment] 2023-09-15 15:48
This is a duplicate of #225.

**Closed by dtolnay** 2023-09-15 15:48 UTC

**Comment by koenichiwa** [comment] 2023-09-15 16:34
Oh wow interesting! For future reference for  anyone else: a workaround would be to add a single pass test, which only has an empty main function, and running it before any compilation fail tests, like so:
```rust
let t = trybuild::TestCases::new();
t.pass("tests/pass/empty_pass.rs");
t.compile_fail("tests/compile_fail/actual_test.rs");
```
This triggers trybuild to use cargo build instead of cargo test.

It's not guaranteed that it will actually work though because the compiler might not evaluate all constant values at compile time.
