### ISSUE TITLE
can't make HTTP request in the offline mode

### ISSUE THREAD

**Issue by TriplEight** [dtolnay/trybuild#52] opened 2020-03-09 17:52 UTC
Now with trybuild [v1.0.23](https://github.com/dtolnay/trybuild/pull/51/files) I'm always having
```
 running 1 test
error: failed to download `quote v1.0.2`
Caused by:
  can't make HTTP request in the offline mode
test compile_tests ... FAILED
```
And to avoid it I always have to do `cargo update/upgrade` which is not always possible.
Why does trybuild require the latest versions of the deps, why are you expecting them to be in cache? And why do you require the raw cargo (this is more out of interest, because AFAIU it prevents using wrappers such as `sccache`)?

**Comment by CreepySkeleton** [comment] 2020-03-09 18:07
This is probably due to https://github.com/dtolnay/trybuild/pull/51

**Comment by TriplEight** [comment] 2020-03-09 18:12
> This is probably due to #51

correct, but also I do not clearly understand why does it require the latest deps every time.

**Comment by dtolnay** [comment] 2020-03-09 18:53
Can you share steps to reproduce this? Does it only happen if using sccache for the outer `cargo test` invocation?

The crate compiled by trybuild is given the same dependencies as the outer crate has, so given that the trybuild invocation happens during a run of `cargo test` of the outer crate, we know there must be a combination of versions of the dependencies in offline cache satisfying the requirements. It's possible that in order for Cargo to figure that out we need to mirror the outer crate's Cargo.lock into the directory of the crate being built.

FYI @thomaseizinger

**Comment by TriplEight** [comment] 2020-03-09 19:31
This is the example pipeline which fails: https://gitlab.parity.io/parity/ink/-/jobs/411481
Now working on a way to reproduce it locally.

**Comment by TriplEight** [comment] 2020-03-09 21:08
And [this](https://gitlab.parity.io/parity/ink/-/jobs/411625) job succeded after I removed the cache (`CARGO_HOME` and `CARGO_TARGET_DIR` which are stored separately from the repos). 
Both caches are heavily used by CI and stored like this:
```
CARGO_HOME = "/ci-cache/$PROJECT_NAME/cargo/$CI_JOB_NAME"
CARGO_TARGET_DIR = "/ci-cache/$PROJECT_NAME/target/$branch/$CI_JOB_NAME"
```
This means that next time some `quote` dependency will update to a `v1.0.4` CI will fail until someone will do `cargo upgrade`.

**Comment by TriplEight** [comment] 2020-03-09 21:20
Also, I've noticed `target` dirs are appearing in the workspace's members' dirs( as in `examples/incrementer/target/`). Which prevents these tests from using  an external `CARGO_TARGET_DIR`

**Comment by TriplEight** [comment] 2020-03-09 21:47
I dug further and [got](https://gitlab.parity.io/parity/ink/-/jobs/411640) a green test after cleaning `$CARGO_TARGET_DIR/test/tests/`

**Comment by dtolnay** [comment] 2020-03-09 22:02
On the dependencies not being found in offline cache because an old Cargo.lock is being cached, I filed #53 to follow up.

On the rogue `target` dirs, our choice of where to put things is based on shelling to `cargo metadata` which should respect any CARGO_TARGET_DIR that is set. It would be good to get a local repro of the bad behavior.

**Comment by TriplEight** [comment] 2020-03-09 22:09
> I dug further and [got](https://gitlab.parity.io/parity/ink/-/jobs/411640) a green test after cleaning `$CARGO_TARGET_DIR/test/tests/`

more precisely. I've found where did it take another versions of the deps: from `$CARGO_TARGET_DIR/test/tests/<workspace member>/Cargo.lock`, it had `quote v1.0.2`

**Comment by dtolnay** [comment] 2020-03-09 22:11
Yep, that's what I meant about an old Cargo.lock being in cache from a previous run.

**Comment by TriplEight** [comment] 2020-03-09 22:17
>  It would be good to get a local repro of the bad behavior.

I think I'll be able to supply you with it tomorrow. Just unsure how to share the archive with old cache and `Cargo.lock`.

**Comment by dtolnay** [comment] 2020-03-09 22:22
The old cache and Cargo.lock hopefully isn't necessary to reproduce failing to respect CARGO_TARGET_DIR. I think those are two separate issues.

**Comment by TriplEight** [comment] 2020-03-09 22:23
I wasn't been able to repro with a clean `CARGO_TARGET_DIR` cache, like in https://github.com/dtolnay/trybuild/issues/52#issuecomment-596795588

**Comment by dtolnay** [comment] 2020-03-09 22:27
Sounds good, in that case I'll close this in favor of #53.

**Closed by dtolnay** 2020-03-09 22:27 UTC
