### ISSUE TITLE
failed to execute cargo: No such file or directory

### ISSUE THREAD

**Issue by TriplEight** [dtolnay/trybuild#47] opened 2020-02-14 17:43 UTC
With the update to the latest version `trybuild v1.0.21` we've started to get this error:
```
ERROR: failed to execute cargo: No such file or directory (os error 2)
test ui ... FAILED
failures:
---- ui stdout ----
thread 'ui' panicked at 'tests failed', /ci-cache/substrate/cargo/test-linux-stable/registry/src/github.com-1ecc6299db9ec823/trybuild-1.0.21/src/run.rs:38:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/io/mod.rs:1426
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:156
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:207
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  12: std::panicking::begin_panic
  13: <trybuild::TestCases as core::ops::drop::Drop>::drop
  14: core::ops::function::FnOnce::call_once
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/liballoc/boxed.rs:1022
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  17: std::panicking::try
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/panicking.rs:270
  18: std::panic::catch_unwind
             at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/panic.rs:394
  19: test::run_test_in_process
             at src/libtest/lib.rs:567
  20: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:474
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
failures:
    ui
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
error: test failed, to rerun pass '-p frame-support-test --test construct_runtime_ui'
Command exited with non-zero status 101
```
And test's code is: https://github.com/paritytech/substrate/blob/master/frame/support/test/tests/construct_runtime_ui.rs

**Comment by dtolnay** [comment] 2020-02-14 19:33
This didn't reproduce for me -- running `cargo test` in substrate/frame/support/test runs the UI tests on my machine.

You said this started with the upgrade to 1.0.21. Which previous version worked before?

The error "failed to execute cargo: No such file or directory (os error 2)" would happen if trybuild isn't able to invoke Cargo. The way we pick a Cargo to run is:

```rust
option_env!("CARGO").unwrap_or("cargo")
```

which has been the same since trybuild 1.0.0. The environment variable CARGO is set by Cargo to point to itself when building a crate (https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates). Is there something that might have changed in your build environment so that CARGO would refer somewhere that doesn't exist, or not be set?

**Comment by TriplEight** [comment] 2020-02-20 09:38
Hey,
so I've been investigating the issue and tried it with `CARGO_HOME` unset. Our CI relies heavily on caching, `CARGO_HOME` is shared between builds. Here:

https://gitlab.parity.io/parity/substrate/-/jobs/392484#L1937 with the usual CI setup;
https://gitlab.parity.io/parity/substrate/-/jobs/392343#L546 this is where I removed `CARGO_HOME` (and tried to fix tests, but it turned not to be related)
https://gitlab.parity.io/parity/substrate/-/jobs/392486 and here I removed the fixes and it succeeded.
Seems like something's wrong with not default `CARGO_HOME`.

**Comment by TriplEight** [comment] 2020-02-21 13:15
FYI, it doesn't seem to reproduce on `1.0.23`.

**Comment by dtolnay** [comment] 2020-02-21 18:14
I'll go ahead and close this. The only two code changes between 1.0.21 and 1.0.23 were 91a0b10a6ee2753594154491679f5b38452c337e and 24a173f9c99f4d23323b29e43bc1e2e1a835a266, and it's obvious to me that neither of those would have any relation to this issue.

**Closed by dtolnay** 2020-02-21 18:14 UTC
