### ISSUE TITLE
`cargo build` needed for panics in constant expressions

### ISSUE THREAD

**Issue by Jarcho** [dtolnay/trybuild#230] opened 2023-04-04 02:33 UTC
Currently `cargo check` will not evaluate associated constants or const blocks. This results in `cargo check` succeeding while `cargo build` fails to compile when it evaluates the constant.

Example
```rust
trait A { const A: (); }
impl A for () { const A: () = panic!(); }

fn main() {
    <() as A>::A;
}
```

This s probably best done with a `force_eval_constants` flag which would switch to using `cargo build` for any rust version (currently all of them) for which `cargo check` will miss constant panics.

**Comment by dtolnay** [comment] 2023-04-04 02:35
This is a duplicate of #225.

**Closed by dtolnay** 2023-04-04 02:35 UTC
